newquiz/urls.py
from django.urls import path
from .views import (
    QuizListView,
    quiz_view,
    quiz_data_view,
    save_quiz_view,
    quiz_first_page,
    form_thanks_view,
    
)

app_name = 'newquiz'

urlpatterns = [
    path('<pk>/thanks/', form_thanks_view, name="formthanks"),
    path('', QuizListView.as_view(), name="main"),
   
    path('<pk>/', quiz_view, name='quiz-view'),
    path('<pk>/save/', save_quiz_view, name='save-view'),
    path('<pk>/data/', quiz_data_view, name='quiz-data-view'),
    path('q/quiz/<pk>/',quiz_first_page, name='first-view'),
    
]

quiz/urls.py
from django.urls import path
from quiz import views

app_name = "quiz"

urlpatterns = [
   
    path(
        
        "<int:form_id>/question/<int:question_id>/",
        views.AnswerQuestionView.as_view(),
        name="answer_form_question",
    ),
    path("<int:form_id>/thanks/", views.FormThanksView.as_view(), name="form_thanks"),
    path("out-of-time/", views.FormNoTimeView.as_view(), name="form_thanks"),
    path("<int:form_id>/", views.FormView.as_view(), name="form_main"),
    path('form/<int:form_id>/result/', views.ResultView.as_view(), name='result')
]

quizapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("maliyo-admin/", admin.site.urls),
    path("", include("quiz.urls", "quiz")),
    path("newquiz/", include("newquiz.urls")),
]

newquiz/models.py
from django.db import models
from django.contrib.auth.models import User
import random

DIFF_CHOICES = (
    ('easy', 'easy'),
    ('medium', 'medium'),
    ('hard', 'hard'),
)

class Quiz(models.Model):
    name = models.CharField(max_length=120)
    topic = models.CharField(max_length=120)
    number_of_questions = models.IntegerField()
    time = models.IntegerField(help_text="duration of the quiz in minutes")
    required_score_to_pass = models.IntegerField(help_text="required score in %")
    difficluty = models.CharField(max_length=6, choices=DIFF_CHOICES)

    def __str__(self):
        return f"{self.name}-{self.topic}"

    def get_questions(self):
        questions = list(self.question_set.all())
        
        return questions[:self.number_of_questions]

    class Meta:
        verbose_name_plural = 'Quizes'

class Question(models.Model):
    text = models.CharField(max_length=200)
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.text)

    def get_answers(self):
        return self.answer_set.all()

class Answer(models.Model):
    text = models.CharField(max_length=200)
    correct = models.BooleanField(default=False)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"question: {self.question.text}, answer: {self.text}, correct: {self.correct}"

class Result(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    score = models.FloatField()
    def __str__(self):
        return str(self.pk)

# Create your models here.

quiz/forms.py
from django import forms
from quiz.models import UserResponse


class UserResponseCreateForm(forms.ModelForm):
    class Meta:
        model = UserResponse
        fields = ["question", "form", "selected_options", "user_value", "user_ip"]


# class Question

newquiz/views.py
from django.shortcuts import render
from .models import Quiz, Question, Answer, Result
from django.views.generic import ListView, TemplateView
from django.http import JsonResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponse


class QuizListView(ListView):
    model = Quiz 
    template_name = 'main.html'

def quiz_first_page (request,pk):
    quiz = Quiz.objects.get(pk=pk)
    questions = quiz.get_questions()
    return render(request, 'newquiz.html',{'quiz':quiz, 'questions':questions})

def quiz_view(request, pk):
   quiz = Quiz.objects.get(pk=pk)
   questions = quiz.get_questions()
   paginator = Paginator(questions, 1) # Show 1 question per page
   page_number = request.GET.get('page')
   page_obj = paginator.get_page(page_number)
   return render(request, 'quiz.html', {'obj':quiz, 'page_obj': page_obj})

def quiz_data_view(request, pk):
    quiz = Quiz.objects.get(pk=pk)
    questions = []
    for q in quiz.get_questions():
        answers = []
        for a in q.get_answers():
            answers.append(a.text)
        questions.append({str(q): answers})
    return JsonResponse({
        'data': questions,
        'time': quiz.time,
    })
def form_thanks_view(request,pk):
    quiz = Quiz.objects.get(pk=pk)
    return render(request, 'formthanks.html',{'quiz':quiz})
def save_quiz_view(request, pk):
    if request.is_ajax():
        questions = []
        data = request.POST
        data_ = dict(data.lists())

        data_.pop('csrfmiddlewaretoken')

        for k in data_.keys():
            print('key: ', k)
            question = Question.objects.get(text=k)
            questions.append(question)
        print(questions)

        user = request.user
        quiz = Quiz.objects.get(pk=pk)

        score = 0
        multiplier = 100 / quiz.number_of_questions
        results = []
        correct_answer = None

        for q in questions:
            a_selected = request.POST.get(q.text)

            if a_selected != "":
                question_answers = Answer.objects.filter(question=q)
                for a in question_answers:
                    if a_selected == a.text:
                        if a.correct:
                            score += 1
                            correct_answer = a.text
                    else:
                        if a.correct:
                            correct_answer = a.text

                results.append({str(q): {'correct_answer': correct_answer, 'answered': a_selected}})
            else:
                results.append({str(q): 'not answered'})
            
        score_ = score * multiplier
        Result.objects.create(quiz=quiz, user=user, score=score_)

        results.append({'score': score_})

        if score_ >= quiz.required_score_to_pass:
            return JsonResponse({'passed': True, 'results': results})
        else:
            return JsonResponse({'passed': False, 'results': results})
    else:
        return HttpResponse("This view only accepts AJAX requests.")

quiz/views.py
from django.urls import reverse, reverse_lazy
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import View, ListView, CreateView, DetailView, TemplateView
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from quiz.models import Question, Form, UserResponse
from quiz.forms import UserResponseCreateForm
from quiz.utils import get_client_ip


class AnswerQuestionView(View):
    def get(self, request: HttpRequest, form_id: int, question_id: int):
        question: Question = get_object_or_404(Question, form=form_id, pk=question_id)
        form = Form.objects.filter(pk=form_id).first()
        next_questions = form.get_next_questions(question)
        return render(
            request,
            "answer_question.html",
            context={
                "form": form,
                "question": question,
                "next_questions": next_questions,
            },
        )

    def post(self, request: HttpRequest, form_id: int, question_id: int):
        question: Question = get_object_or_404(Question, form=form_id, pk=question_id)
        form = Form.objects.filter(pk=form_id).first()
        next_questions = form.get_next_questions(question)
        

        data = request.POST.dict()
       
        data["user_ip"] = get_client_ip(request)
        data["selected_options"] = request.POST.getlist("selected_options", [])
        user_response_form = UserResponseCreateForm(data)

        if user_response_form.is_valid():
            instance = user_response_form.save()
            
            next_question = next_questions.first()
            if next_question:
                
                return redirect(
                    "quiz:answer_form_question",
                    **{"form_id": form.pk, "question_id": next_question.pk},
                )
            else:
                return redirect("quiz:form_thanks", **{"form_id": form.pk})
        else:
           
            return render(
                request,
                "answer_question.html",
                context={
                    "form": form,
                    "question": question,
                    "next_questions": next_questions,
                    "form_errors": user_response_form.errors,
                },
            )


class FormView(View):
    def get(self, request: HttpRequest, form_id: int) -> HttpResponse:
        form: Form = get_object_or_404(Form, pk=form_id)
        form_questions = form.get_ordered_questions()
        return render(
            request,
            "form_main.html",
            context={"form": form, "form_questions": form_questions},
        )


class FormThanksView(TemplateView):
    template_name = "form_thanks.html"

class FormNoTimeView(TemplateView):
    template_name = "form_time_over.html"

class ShowFirstQuestionView(View):
    def get(self, request: HttpRequest, form_id: int, question_id: int):
        question: Question = get_object_or_404(Question, form=form_id, pk=question_id)
        form = Form.objects.filter(pk=form_id).first()
        
        return render(
            request,
            "answer_question.html",
            context={
                "form": form,
                "question": question,
                
            },
        )
class ResultView(View):
    def get(self, request: HttpRequest, form_id: int):
        form = get_object_or_404(Form, id=form_id)
        questions = form.questions.all()
        score = 0
        for question in questions:
            correct_option = 4
            user_answer = 4
            print(correct_option)
            
            if user_answer == correct_option:
                score += question.score_amount
        return render(request, 'form_results.html', {'score': score})
def bootstrap4_index(request):
    return render(request, "form_thanks.html", {})



# Create your views here.

newquiz/templates/formthanks.html
{% extends "top.html" %} {% load static %}{% block title %}Thank You!{% endblock title %}
{% block scripts %}
<script src="{% static 'thanks.js' %}" defer></script> 
    
{% endblock scripts %}
{% block content %}
<div id="other" class="card col-8 mx-auto container mt-3 text-center mx-auto d-flex align-items-center justify-content-center" >

<div class="card-body text-center">
      <h5 class="card-title">Thank You for Filing the form 🚀  🚀</h5>
      
      <h5 class="card-title" id="scoreCard" score-pass="{{quiz.required_score_to_pass}}">Score: {{score}}</h6>
      <div id="progressBar">
        <div id="filled"></div>
   </div>
   <p class="card-text">Your response has been recorded</p>
   <div id="imageSpace">

   </div>
  
      
     <br>
<a href="{% url 'newquiz:first-view' quiz.pk%}"><button id="home" class="btn modal-button btn btn-success">Home</button></a>
      

 
</div>
</div>
{% endblock content %}

newquiz/templates/main.html
{% extends "top.html" %}
{% load static %}

{% block scripts %}
    <script src="{% static 'main.js' %}" defer></script> 
{% endblock scripts %}

{% block title %}
home
{% endblock title %}

{% block content %}

<!-- Modal -->
<div class="modal fade" id="quizStartModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Start?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="modal-body-confirm"></div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">no</button>
        <button type="button" id="start-button" class="btn btn-success">yes</button>
      </div>
    </div>
  </div>
</div>

<div class="h1" id="quiz-heading">Quiz List</div>
<hr>
{% for questions in questions %}
    {% if forloop.first %}
    <button
            class="btn btn-link modal-button"
            data-pk="{{questions.pk}}"
            data-quiz="{{quiz.name}}"
            data-questions="{{quizj.number_of_questions}}"
            data-difficulty="{{quiz.difficluty}}"
            data-time="{{quiz.time}}"
            data-pass = "{{quiz.required_score_to_pass}}"
            data-toggle="modal"
            data-target="#quizStartModal"
            id="startbutton" onClick="">Start
            "{{quiz.name}}" </button>
            {% endif %} {% endfor %}<br>


{% endblock content %}

newquiz/templates/newquiz.html
{% extends "top.html" %}
{% load static %}

{% block scripts %}

    <script src="{% static 'home.js' %}" type="module" defer></script> 
    
{% endblock scripts %}

{% block title %}
{{obj.name}}

{% endblock title %}

{% block content %}
<div id="other" class="card col-8 mx-auto container mt-3 text-center mx-auto d-flex align-items-center justify-content-center" >
      
<hr>
<div class="card-title"><b>{{quiz.name}}</b></div>
<div class="card-subtitle mb-2 text-muted">{{quiz.topic}}</div>

<p class="card-text">Questions for <b>{{ quiz.name }}</b>.</p>
<br>
{% for questions in questions %}

    {% if forloop.first %}
    
    <button
            class="btn modal-button btn btn-success"
            data-pk="{{quiz.pk}}"
            data-quiz="{{quiz.name}}"
            data-questions="{{quizj.number_of_questions}}"
            data-difficulty="{{quiz.difficluty}}"
            data-time="{{quiz.time}}"
            data-pass = "{{quiz.required_score_to_pass}}"
            data-toggle="modal"
            data-target="#quizStartModal"
            id="startbutton" onClick="">Start Quiz</button>
           
            {% endif %} {% endfor %}<br>
   
{% endblock content %}
</div>

newquiz/templates/quiz.html
{% extends "top.html" %}
{% load static %}

{% block scripts %}
    
    <script src="{% static 'test.js' %}" defer ></script> 
    <script src="{% static 'newtimer.js' %}"></script> 
{% endblock scripts %}
{% block styles %}
<style>
.btn-option {
    max-width: 100px;
    max-height: 50px;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
}
</style>
{% endblock styles %}
{% block title %}
{{obj.name}}
{% endblock title %}

{% block content %}
<div id="help" pk-id="{{obj.pk}}"></div>
<div id="loader"><div class="square"></div></div>
<div id="main" class="col-11"  style="visibility: hidden;">
   <div class="card w-100 card-body text-center" >
            
            <div class="card-body text-center" id="newcard">
                <form id="quiz-form" class="mt-3 mb-3">
                    {% csrf_token %}
                    
                    <div class="col text-center" id="timer-box"></div>
                    <hr>
                
                    <h2 id="showQuestion"></h2>
                    
                    <div id="progress-bar" total-questions="{{obj.number_of_questions}}"><div id="fill"></div></div>
                    
                    <br>
                    {% for question in page_obj %}
                        <h2 class="card-title">{{question.text}}</h2>
                        
                        <p class="card-text">Pick an option:</p>
                        <div class="answers row align-items-center">
                            {% for answer in question.get_answers %}
                                
                                <div class="col-sm-3 col-sm-6 form-group">
                                    {% if page_obj.has_next %}
                                        <a href="?page={{ page_obj.next_page_number }}">
                                        <button
                                            type="button"
                                            name="{{ obj.value }}"
                                            data-pk="{{ obj.pk }}"
                                            id="{{ answer.pk }}"
                                            class="btn btn-outline-primary btn-option btn-block"
                                            value="{{ obj.value }}"
                                            data-time="{{obj.time}}"
                                            data-correct="{{ answer.correct }}"
                                        >
                                            {{answer.text}}
                                        </button></a>
                                        {% else %}
                                        <a href="{% url 'newquiz:formthanks' obj.pk%}">
                                            <button
                                            type="button"
                                            name="{{ obj.value }}"
                                            data-pk="{{ obj.pk }}"
                                            id="{{ answer.pk }}"
                                            class="btn btn-outline-primary btn-option btn-block"
                                            value="{{ obj.value }}"
                                            data-time="{{obj.time}}"
                                            data-correct="{{ answer.correct }}"
                                        >
                                            {{answer.text}}
                                        </button></a>
                                        {% endif %}
                                </div>
                            {% endfor %}
                        </div>
                    {% endfor %}
                    <div id="result-message"></div>
                    <hr>
                    
            </form></div></div></div>
{% endblock content %}

newquiz/templates/top.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- favicon -->
    
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <!-- jquery -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>

    <!-- custom css & js-->
    <link rel="stylesheet" href="{% static 'newquizstylee.css'%}" rel="stylesheet" />
    
    <script type="text/javascript">
      window.history.forward();
      function noBack() {
          window.history.forward();
      }
  </script>

    {% block scripts %}
    {% endblock scripts %}

    <title>quiz app| {% block title %}{% endblock title %}</title>
  </head>
  <body>
    <div>
      <div id="outerContainer" class="container-fluid d-flex align-items-center justify-content-center" >
        <div id="containerA" class="animation-area">
         
          
          <ul class="box-area">
            
            <li></li>
            <li></li>
            <li></li>
            
            
            
            
          </ul>
          
        </div>
        
            
          
          
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    
    
    
    </div>
    
     
    </div>
    
    <div id="containerB" class="w-100 h-100 row justify-content-center align-items-center text-center">
            {% block content %}
            {% endblock content %}
            </div>
     
    

    <div class="rest-of-page" >j</div>
  
          
          
      
  </body>
  
</html>